### ISSUE TITLE
Rust Fundamentals missing slides

### ISSUE THREAD

**Issue by miguelraz** [ferrous-systems/rust-training#12]
## Introduction and History

-   [x] [Overview](https://github.com/ferrous-systems/rust-training/blob/main/training-slides/src/overview.md)
-   [x] [Installation](https://github.com/ferrous-systems/rust-training/blob/main/training-slides/src/installation.md)

## Basic Types, Functions and Control Flow

-   [x] [Basic Types](https://github.com/ferrous-systems/rust-training/blob/main/training-slides/src/basic-types.md)
-   [x] [Control Flow](https://github.com/ferrous-systems/rust-training/blob/main/training-slides/src/control-flow.md)

## Compound Types & match

-   [x] [Compound Types](https://github.com/ferrous-systems/rust-training/blob/main/training-slides/src/compound-types.md)

## Ownership and Borrowing

-   [x] [Ownership and Borrowing](https://github.com/ferrous-systems/rust-training/blob/main/training-slides/src/ownership.md)

## Error Handling

-   [x] [Error Handling](./error-handling.md) 

## Collection Types & Iterators

-   [x] [Collections](https://github.com/ferrous-systems/rust-training/blob/main/training-slides/src/collections.md) 
-   [x] [Iterators](https://github.com/ferrous-systems/rust-training/blob/main/training-slides/src/iterators.md) (#20)

## Library Design

-   [x] [Imports and Modules](https://github.com/ferrous-systems/rust-training/blob/main/training-slides/src/imports-and-modules.md) #22
-   [x] [Good Design Practices](https://github.com/ferrous-systems/rust-training/blob/main/training-slides/src/good-design-practices.md)

**Comment by jonathanpallant** [comment]
This list should follow the updated list in SUMMARY.md, which is based on https://ferroussystems.hackmd.io/B9Tn0NCdT2WqYEDR0rCIOA.
