### ISSUE TITLE
Logo is borked when serving slides locally

### ISSUE THREAD

**Issue by miguelraz** [ferrous-systems/rust-training#134]
I get this

<img width="862" alt="image" src="https://github.com/ferrous-systems/rust-training/assets/13056181/912ebed6-d167-4805-9b4c-cb678d12bc3f">

When running either `httplz ./slides` or the `python` server call.

The python script fortunately does print a 404:

```
❯ python3 -m http.server -d ./slides
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::1 - - [25/Feb/2024 13:44:39] "GET /overview.html HTTP/1.1" 200 -
::1 - - [25/Feb/2024 13:44:39] code 404, message File not found
::1 - - [25/Feb/2024 13:44:39] "GET /images/logo_ferrous-systems_rgb.png HTTP/1.1" 404 -
```

Opening up the slides from the released artifacts doesn't show up any problems, so I'm punting on this after the training, but still wanted to log it.

**Comment by jonathanpallant** [comment]
How did you build the HTML? I think the build.sh file copies over the images because mdslides does not.

**Comment by miguelraz** [comment]
Right, Windows doesn't work and I skipped that step. Manually doing it fixed it.

**Comment by jonathanpallant** [comment]
Ahh, we should maybe have a build.ps1 file. Or you could use WSL?

**Comment by miguelraz** [comment]
I bailed on learning powershell and started using `nushell` for everything, but yes, that would be a nice addition.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
