### ISSUE TITLE
Tell the compiler to use specific order

### ISSUE THREAD

**Issue by plaindocs** [ferrous-systems/rust-training#181]
In `compound-types.md` L18 we say

> The fields may not be laid out in memory in the order they are written (unless
you ask the compiler to ensure that they are).

but we don't mention how to do that. If we don't want to dig in at this stage we should maybe at least link it

**Comment by miguelraz** [comment]
Good catch!

I like the idea of linking to `#[repr(C)]`, but at this point in the training we haven't introduce `#[macros]` yet, so I think a small link as a breadcrumb is fine for the people that want to venture forth but I don't want too add too much context too soon. 

I don't feel that strongly about it and am glad to rephrase the PR.
