### ISSUE TITLE
Should examples include fn main?

### ISSUE THREAD

**Issue by jonathanpallant** [ferrous-systems/rust-training#2]
This works in mdbook and mdslides:

```rust
let x = 6;
```

It will pass the tests. However, if you load it into the playground with the RUN button it won't work.

The playground requires you write it out in full:

```rust
fn main() {
    let x = 6;
}
```

Which is better?

**Comment by amanjeev** [comment]
I feel it is alright to include the full version if we want users to be able to run it.  If we want only the first one, I would remove the Run button.  I also do not want to hack any JS to add the `fn main()` part. 

One other idea is to include a playground link at the bottom of each code snippet, and remove the Run button from code snippet. That way folks get a succinct code version with a link to playground to run it.

**Comment by jonathanpallant** [comment]
mdbook supports the idea of hiding lines of code by prefixing them with `#`, but I don't know how we'd teach highlight.js about this.

Maybe it's best to just make the examples fully runnable. Saves the trainer having to manually add the `fn main() {` and `}` after they've opened the playground.

**Comment by amanjeev** [comment]
I vote for full.  two extra lines for runnable code yea i am ok with that.

**Comment by jonathanpallant** [comment]
Agreed
