### ISSUE TITLE
Lifetimes: Reword the slide about `takes_and_returns` 

### ISSUE THREAD

**Issue by amanjeev** [ferrous-systems/rust-training#86]
Slide code: https://github.com/ferrous-systems/rust-training/blob/main/training-slides/src/lifetimes.md?plain=1#L95

This function CAN return local data 

```rust
fn takes_and_returns(s: &str) -> &str {
    "abc"
}
```

**Comment by jonathanpallant** [comment]
s/local/static. A string literal isn't local - it's a string slice with static lifetime.

**Comment by jonathanpallant** [comment]
I think the note to add here is that whilst you can return a slice with static lifetime, the borrow checker can only assume the lifetime of the output is tied to the lifetime of the input, so you must drop the returned slice before dropping the input slice, even if you did return `"abc"`.

**Comment by jonathanpallant** [comment]
We fixed this.
